apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
  - image: busybox
    command: ["sh"]
    args: ["-c", "echo hello; sleep 3600"]
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always